/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package gitops

import (
	"context"
	"fmt"

	"github.com/mbergo/smooth-operator/internal/executor"
	"github.com/mbergo/smooth-operator/internal/llm"
	"github.com/mbergo/smooth-operator/internal/planner"
	"sigs.k8s.io/controller-runtime/pkg/log"
)

// Agent orchestrates GitOps operations after successful execution
type Agent struct {
	helmGenerator      *HelmChartGenerator
	rationaleGenerator *RationaleGenerator
	gitClient          *GitClient
}

// NewAgent creates a new GitOps agent
func NewAgent() *Agent {
	return &Agent{
		helmGenerator:      NewHelmChartGenerator(),
		rationaleGenerator: NewRationaleGenerator(),
		gitClient:          NewGitClient(),
	}
}

// ProcessSuccessfulExecution handles GitOps after successful apply
func (a *Agent) ProcessSuccessfulExecution(
	ctx context.Context,
	chatSessionName string,
	userPrompt string,
	gitRepo string,
	gitPath string,
	llmResponse *llm.LLMResponse,
	executionPlan *planner.Plan,
	executionResult *executor.ExecutionResult,
) (*GitCommitResult, error) {
	log := log.FromContext(ctx)

	log.Info("Processing GitOps artifacts",
		"chatSession", chatSessionName,
		"repo", gitRepo,
		"path", gitPath,
	)

	// 1. Generate Helm chart
	appName := extractAppName(gitPath)
	chart, err := a.helmGenerator.GenerateChart(appName, "", executionResult)
	if err != nil {
		return nil, fmt.Errorf("failed to generate Helm chart: %w", err)
	}

	log.Info("Helm chart generated", "name", chart.Name, "files", len(chart.Files))

	// 2. Generate SMOOTH.md rationale
	rationale := a.rationaleGenerator.GenerateRationale(
		chatSessionName,
		userPrompt,
		llmResponse,
		executionPlan,
		executionResult,
	)

	log.Info("SMOOTH.md rationale generated", "length", len(rationale))

	// 3. Commit to Git
	gitOptions := GitOptions{
		RepoURL:       gitRepo,
		BaseBranch:    "main",
		CommitMessage: fmt.Sprintf("feat(smooth): %s\n\nGenerated by Smooth Operator\nChatSession: %s", appName, chatSessionName),
		CommitMode:    "pr", // Default to PR mode
		Reviewers:     []string{},
	}

	commitResult, err := a.gitClient.CommitAndPush(ctx, gitOptions, chart, rationale, chatSessionName)
	if err != nil {
		return nil, fmt.Errorf("Git operations failed: %w", err)
	}

	log.Info("GitOps processing complete",
		"success", commitResult.Success,
		"commitSHA", commitResult.CommitSHA,
		"prURL", commitResult.PRURL,
	)

	return commitResult, nil
}

// extractAppName gets app name from git path
func extractAppName(gitPath string) string {
	parts := []string{}
	for _, part := range []rune(gitPath) {
		if part == '/' {
			parts = append(parts, string(part))
		}
	}
	
	if len(parts) > 0 {
		return parts[len(parts)-1]
	}
	return "app"
}

