/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package gitops

import (
	"fmt"
	"strings"

	"github.com/mbergo/smooth-operator/internal/executor"
)

// HelmChartGenerator creates Helm charts from applied resources
type HelmChartGenerator struct{}

// NewHelmChartGenerator creates a new Helm chart generator
func NewHelmChartGenerator() *HelmChartGenerator {
	return &HelmChartGenerator{}
}

// GenerateChart creates a Helm chart from execution results
func (h *HelmChartGenerator) GenerateChart(
	appName string,
	namespace string,
	executionResult *executor.ExecutionResult,
) (*HelmChart, error) {
	chart := &HelmChart{
		Name:      appName,
		Namespace: namespace,
		Files:     make(map[string]string),
	}

	// Generate Chart.yaml
	chart.Files["Chart.yaml"] = h.generateChartYAML(appName)

	// Generate values.yaml
	chart.Files["values.yaml"] = h.generateValuesYAML(executionResult)

	// Generate templates for each resource
	for _, resource := range executionResult.AppliedResources {
		templateName := fmt.Sprintf("templates/%s.yaml", strings.ToLower(resource.Kind))
		chart.Files[templateName] = h.generateTemplate(resource)
	}

	// Generate NOTES.txt
	chart.Files["templates/NOTES.txt"] = h.generateNotes(appName, executionResult)

	return chart, nil
}

// generateChartYAML creates Chart.yaml content
func (h *HelmChartGenerator) generateChartYAML(appName string) string {
	return fmt.Sprintf(`apiVersion: v2
name: %s
description: A Helm chart generated by Smooth Operator
type: application
version: 0.1.0
appVersion: "1.0"
annotations:
  smooth.k8s.io/generated: "true"
  smooth.k8s.io/generator: "smooth-operator"
`, appName)
}

// generateValuesYAML creates values.yaml content
func (h *HelmChartGenerator) generateValuesYAML(executionResult *executor.ExecutionResult) string {
	return `# Default values for smooth-generated chart
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: ""

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

# Smooth Operator metadata
smooth:
  generated: true
  timestamp: "` + executionResult.AppliedResources[0].AppliedAt.Format("2006-01-02T15:04:05Z") + `"
`
}

// generateTemplate creates a template file for a resource
func (h *HelmChartGenerator) generateTemplate(resource executor.AppliedResource) string {
	return fmt.Sprintf(`# Generated by Smooth Operator
# Resource: %s
# Operation: %s
# Applied: %s

{{- if .Values.%s.enabled }}
---
# TODO: Templatize this resource
# For now, this is a placeholder
apiVersion: v1
kind: %s
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
{{- end }}
`,
		resource.Name,
		resource.Operation,
		resource.AppliedAt.Format("2006-01-02 15:04:05"),
		strings.ToLower(resource.Kind),
		resource.Kind,
	)
}

// generateNotes creates NOTES.txt
func (h *HelmChartGenerator) generateNotes(appName string, executionResult *executor.ExecutionResult) string {
	var notes strings.Builder

	notes.WriteString("🎉 Thank you for installing " + appName + "!\n\n")
	notes.WriteString("This chart was generated by Smooth Operator.\n\n")
	notes.WriteString("Resources created:\n")

	for i, resource := range executionResult.AppliedResources {
		notes.WriteString(fmt.Sprintf("  %d. %s/%s (%s)\n",
			i+1, resource.Kind, resource.Name, resource.Operation))
	}

	notes.WriteString("\nTo check the status:\n")
	notes.WriteString("  kubectl get all -n {{ .Release.Namespace }}\n")

	return notes.String()
}
