/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package gitops

import (
	"fmt"
	"strings"

	"github.com/mbergo/smooth-operator/internal/executor"
)

// HelmChartGenerator creates Helm charts from applied resources
type HelmChartGenerator struct{}

// NewHelmChartGenerator creates a new Helm chart generator
func NewHelmChartGenerator() *HelmChartGenerator {
	return &HelmChartGenerator{}
}

// GenerateChart creates a Helm chart from execution results
func (h *HelmChartGenerator) GenerateChart(
	appName string,
	namespace string,
	executionResult *executor.ExecutionResult,
) (*HelmChart, error) {
	chart := &HelmChart{
		Name:      appName,
		Namespace: namespace,
		Files:     make(map[string]string),
	}

	// Generate Chart.yaml
	chart.Files["Chart.yaml"] = h.generateChartYAML(appName)

	// Generate values.yaml
	chart.Files["values.yaml"] = h.generateValuesYAML(executionResult)

	// Generate templates for each resource
	for _, resource := range executionResult.AppliedResources {
		templateName := fmt.Sprintf("templates/%s.yaml", strings.ToLower(resource.Kind))
		chart.Files[templateName] = h.generateTemplate(resource)
	}

	// Generate NOTES.txt
	chart.Files["templates/NOTES.txt"] = h.generateNotes(appName, executionResult)

	return chart, nil
}

// generateChartYAML creates Chart.yaml content
func (h *HelmChartGenerator) generateChartYAML(appName string) string {
	return fmt.Sprintf(`apiVersion: v2
name: %s
description: A Helm chart generated by Smooth Operator
type: application
version: 0.1.0
appVersion: "1.0"
annotations:
  smooth.k8s.io/generated: "true"
  smooth.k8s.io/generator: "smooth-operator"
`, appName)
}

// generateValuesYAML creates values.yaml content
func (h *HelmChartGenerator) generateValuesYAML(executionResult *executor.ExecutionResult) string {
	return `# Default values for smooth-generated chart
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: ""

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

# Smooth Operator metadata
smooth:
  generated: true
  timestamp: "` + executionResult.AppliedResources[0].AppliedAt.Format("2006-01-02T15:04:05Z") + `"
`
}

// generateTemplate creates a per-kind Helm template for a resource.
// Each known kind receives full {{ .Values.* }} placeholders; unknown kinds
// fall back to a minimal skeleton so the chart is always valid YAML.
func (h *HelmChartGenerator) generateTemplate(resource executor.AppliedResource) string {
	header := fmt.Sprintf("# Generated by Smooth Operator\n# Resource: %s | Operation: %s | Applied: %s\n",
		resource.Name,
		resource.Operation,
		resource.AppliedAt.Format("2006-01-02 15:04:05"),
	)

	var body string
	switch strings.ToLower(resource.Kind) {
	case "deployment":
		body = generateDeploymentTemplate()
	case "service":
		body = generateServiceTemplate()
	case "horizontalpodautoscaler", "hpa":
		body = generateHPATemplate()
	case "ingress":
		body = generateIngressTemplate()
	case "configmap":
		body = generateConfigMapTemplate()
	default:
		body = generateGenericTemplate(resource.Kind)
	}

	return header + body
}

func generateDeploymentTemplate() string {
	return `apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
`
}

func generateServiceTemplate() string {
	return `apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
`
}

func generateHPATemplate() string {
	return `{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "chart.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
`
}

func generateIngressTemplate() string {
	return `{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.ingressClassName }}
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "chart.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
`
}

func generateConfigMapTemplate() string {
	return `{{- if .Values.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.configMap.data }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
{{- end }}
`
}

func generateGenericTemplate(kind string) string {
	return fmt.Sprintf(`apiVersion: v1
kind: %s
metadata:
  name: {{ include "chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
`, kind)
}

// generateNotes creates NOTES.txt
func (h *HelmChartGenerator) generateNotes(appName string, executionResult *executor.ExecutionResult) string {
	var notes strings.Builder

	notes.WriteString("🎉 Thank you for installing " + appName + "!\n\n")
	notes.WriteString("This chart was generated by Smooth Operator.\n\n")
	notes.WriteString("Resources created:\n")

	for i, resource := range executionResult.AppliedResources {
		notes.WriteString(fmt.Sprintf("  %d. %s/%s (%s)\n",
			i+1, resource.Kind, resource.Name, resource.Operation))
	}

	notes.WriteString("\nTo check the status:\n")
	notes.WriteString("  kubectl get all -n {{ .Release.Namespace }}\n")

	return notes.String()
}
