#!/bin/bash
# Quick script to set OpenAI API key for development

API_KEY="$1"

if [ -z "$API_KEY" ]; then
    echo "Usage: ./scripts/set-api-key.sh YOUR_API_KEY"
    echo ""
    echo "This will create a .env file with your OpenAI API key."
    echo "The .env file is git-ignored for security."
    exit 1
fi

# Create .env file
cat > .env << EOF
# OpenAI API Configuration
# Generated by set-api-key.sh

OPENAI_API_KEY=$API_KEY

# Optional overrides (uncomment to use)
# OPENAI_MODEL=gpt-4-turbo-preview
# OPENAI_MAX_TOKENS=4096
# OPENAI_TEMPERATURE=0.3
# OPENAI_MAX_REQUESTS_PER_MINUTE=10
EOF

echo "✅ API key saved to .env"
echo ""
echo "To run the operator with this key:"
echo "  source .env && make run"
echo ""
echo "To run in-cluster, create a secret:"
echo "  kubectl create secret generic smooth-operator-openai \\"
echo "    --from-literal=api-key=$API_KEY \\"
echo "    -n smooth-operator-system"

